export const typeLookup: StringLookup = {
  file: 'upload',
  title: 'input',
  documentType: 'selectOne',
  fileType: 'selectOne',
  clusters: 'selectMultiple',
  organizations: 'selectMultiple',
  donors: 'selectMultiple',
  washTypes: 'selectMultiple',
  admin1: 'selectMultipleGrouped',
  admin2: 'selectMultipleGrouped',
};

export const dataTpl: Data = {
  id: '',
  file: '',
  title: '',
  documentType: '',
  fileType: '',
  clusters: [],
  organizations: [],
  donors: [],
  washTypes: [],
  admin0: [],
  admin1: [],
  admin2: [],
  createdAt: 0,
  createdBy: '',
  updatedAt: 0,
  updatedBy: '',
  status: '',
};

export const labeledDataTpl: LabeledData = {
  id: '',
  file: '',
  title: '',
  documentType: { label: '', value: '' },
  fileType: { label: '', value: '' },
  clusters: [],
  organizations: [],
  donors: [],
  washTypes: [],
  admin0: [],
  admin1: [],
  admin2: [],
  createdAt: 0,
  createdBy: '',
  updatedAt: 0,
  updatedBy: '',
  status: '',
};

export const schemaHidden: SchemaHidden = {
  admin0: ['SS'],
};

export const schemaStatus: Select = {
  label: 'Status',
  required: true,
  options: {
    DRAFT: 'Draft',
    PUBLISHED: 'Published',
    DELETE: 'Delete',
  },
};

const schema: Schema = {
  upload: {
    file: {
      label: 'File',
      required: true,
    },
  },
  input: {
    title: {
      label: 'Title',
      required: true,
    },
  },
  selectOne: {
    documentType: {
      label: 'Document Type',
      required: true,
      options: {
        MAP: 'Map',
        TERMS_OF_REFERENCE: 'Terms of Reference',
        REPORT: 'Report',
        BASELINE: 'Baseline Assessment',
        ASSESSMENT: 'Assessment',
        FACTSHEET: 'Factsheet',
        DATA: 'Data',
        ODK_TOOL: 'ODK Tool',
      },
    },
    fileType: {
      label: 'File Type',
      required: true,
      options: {
        PDF: 'PDF',
        DOCX: 'Word',
        XLSX: 'Excel',
        PPTX: 'PowerPoint',
        CSV: 'CSV',
        ZIP: 'ZIP',
      },
    },
  },
  selectMultiple: {
    clusters: {
      label: 'Clusters',
      required: true,
      options: {
        CCCM: 'Camp Coordination and Camp Management',
        EDUCATION: 'Education',
        FSL: 'Food Security and Livelihoods',
        HEALTH: 'Health',
        LOGISTICS: 'Logistics',
        NUTRITION: 'Nutrition',
        PROTECTION: 'Protection',
        SHELTER: 'Shelter',
      },
    },
    organizations: {
      label: 'Organizations',
      required: true,
      options: {
        REACH: 'REACH',
        ACTED: 'ACTED',
      },
    },
    donors: {
      label: 'Donors',
      required: true,
      options: {
        UNICEF: 'UNICEF',
        UNHCR: 'UNHCR',
      },
    },
    washTypes: {
      label: 'WASH Types',
      required: true,
      options: {
        WATER: 'Water',
        SANITATION: 'Sanitation',
        HYGIENE: 'Hygiene',
      },
    },
  },
  selectMultipleGrouped: {
    admin1: {
      label: 'Admin 1',
      required: false,
      options: {
        'South Sudan': {
          SS01: 'Central Equatoria',
          SS02: 'Eastern Equatoria',
          SS03: 'Jonglei',
          SS04: 'Lakes',
          SS05: 'Northern Bahr el Ghazal',
          SS06: 'Unity',
          SS07: 'Upper Nile',
          SS08: 'Warrap',
          SS09: 'Western Bahr el Ghazal',
          SS10: 'Western Equatoria',
        },
      },
      submit: {
        SS01: { admin0: 'SS' },
        SS02: { admin0: 'SS' },
        SS03: { admin0: 'SS' },
        SS04: { admin0: 'SS' },
        SS05: { admin0: 'SS' },
        SS06: { admin0: 'SS' },
        SS07: { admin0: 'SS' },
        SS08: { admin0: 'SS' },
        SS09: { admin0: 'SS' },
        SS10: { admin0: 'SS' },
      },
    },
    admin2: {
      label: 'Admin 2',
      required: false,
      options: {
        'Central Equatoria': {
          SS0101: 'Juba',
          SS0102: 'Kajo-keji',
          SS0103: 'Lainya',
          SS0104: 'Morobo',
          SS0105: 'Terekeka',
          SS0106: 'Yei',
        },
        'Eastern Equatoria': {
          SS0201: 'Budi',
          SS0202: 'Ikotos',
          SS0203: 'Kapoeta East',
          SS0204: 'Kapoeta North',
          SS0205: 'Kapoeta South',
          SS0206: 'Lafon',
          SS0207: 'Magwi',
          SS0208: 'Torit',
        },
        Jonglei: {
          SS0301: 'Akobo',
          SS0302: 'Ayod',
          SS0303: 'Bor South',
          SS0304: 'Canal/Pigi',
          SS0305: 'Duk',
          SS0306: 'Fangak',
          SS0307: 'Nyirol',
          SS0308: 'Pibor',
          SS0309: 'Pochalla',
          SS0310: 'Twic East',
          SS0311: 'Uror',
        },
        Lakes: {
          SS0401: 'Awerial',
          SS0402: 'Cueibet',
          SS0403: 'Rumbek Centre',
          SS0404: 'Rumbek East',
          SS0405: 'Rumbek North',
          SS0406: 'Wulu',
          SS0407: 'Yirol East',
          SS0408: 'Yirol West',
        },
        'Northern Bahr el Ghazal': {
          SS0501: 'Aweil Centre',
          SS0502: 'Aweil East',
          SS0503: 'Aweil North',
          SS0504: 'Aweil South',
          SS0505: 'Aweil West',
        },
        Unity: {
          SS0601: 'Abiemnhom',
          SS0602: 'Guit',
          SS0603: 'Koch',
          SS0604: 'Leer',
          SS0605: 'Mayendit',
          SS0606: 'Mayom',
          SS0607: 'Panyijiar',
          SS0608: 'Pariang',
          SS0609: 'Rubkona',
        },
        'Upper Nile': {
          SS0701: 'Baliet',
          SS0702: 'Fashoda',
          SS0703: 'Longochuk',
          SS0704: 'Luakpiny/Nasir',
          SS0705: 'Maban',
          SS0706: 'Maiwut',
          SS0707: 'Malakal',
          SS0708: 'Manyo',
          SS0709: 'Melut',
          SS0710: 'Panyikang',
          SS0711: 'Renk',
          SS0712: 'Ulang',
        },
        Warrap: {
          SS0801: 'Gogrial East',
          SS0802: 'Gogrial West',
          SS0803: 'Tonj East',
          SS0804: 'Tonj North',
          SS0805: 'Tonj South',
          SS0806: 'Twic',
        },
        'Western Bahr el Ghazal': {
          SS0901: 'Jur River',
          SS0902: 'Raja',
          SS0903: 'Wau',
        },
        'Western Equatoria': {
          SS1001: 'Ezo',
          SS1002: 'Ibba',
          SS1003: 'Maridi',
          SS1004: 'Mundri East',
          SS1005: 'Mundri West',
          SS1006: 'Mvolo',
          SS1007: 'Nagero',
          SS1008: 'Nzara',
          SS1009: 'Tambura',
          SS1010: 'Yambio',
        },
      },
      submit: {
        SS0101: { admin0: 'SS', admin1: 'SS01' },
        SS0102: { admin0: 'SS', admin1: 'SS01' },
        SS0103: { admin0: 'SS', admin1: 'SS01' },
        SS0104: { admin0: 'SS', admin1: 'SS01' },
        SS0105: { admin0: 'SS', admin1: 'SS01' },
        SS0106: { admin0: 'SS', admin1: 'SS01' },
        SS0201: { admin0: 'SS', admin1: 'SS02' },
        SS0202: { admin0: 'SS', admin1: 'SS02' },
        SS0203: { admin0: 'SS', admin1: 'SS02' },
        SS0204: { admin0: 'SS', admin1: 'SS02' },
        SS0205: { admin0: 'SS', admin1: 'SS02' },
        SS0206: { admin0: 'SS', admin1: 'SS02' },
        SS0207: { admin0: 'SS', admin1: 'SS02' },
        SS0208: { admin0: 'SS', admin1: 'SS02' },
        SS0301: { admin0: 'SS', admin1: 'SS03' },
        SS0302: { admin0: 'SS', admin1: 'SS03' },
        SS0303: { admin0: 'SS', admin1: 'SS03' },
        SS0304: { admin0: 'SS', admin1: 'SS03' },
        SS0305: { admin0: 'SS', admin1: 'SS03' },
        SS0306: { admin0: 'SS', admin1: 'SS03' },
        SS0307: { admin0: 'SS', admin1: 'SS03' },
        SS0308: { admin0: 'SS', admin1: 'SS03' },
        SS0309: { admin0: 'SS', admin1: 'SS03' },
        SS0310: { admin0: 'SS', admin1: 'SS03' },
        SS0311: { admin0: 'SS', admin1: 'SS03' },
        SS0401: { admin0: 'SS', admin1: 'SS04' },
        SS0402: { admin0: 'SS', admin1: 'SS04' },
        SS0403: { admin0: 'SS', admin1: 'SS04' },
        SS0404: { admin0: 'SS', admin1: 'SS04' },
        SS0405: { admin0: 'SS', admin1: 'SS04' },
        SS0406: { admin0: 'SS', admin1: 'SS04' },
        SS0407: { admin0: 'SS', admin1: 'SS04' },
        SS0408: { admin0: 'SS', admin1: 'SS04' },
        SS0501: { admin0: 'SS', admin1: 'SS05' },
        SS0502: { admin0: 'SS', admin1: 'SS05' },
        SS0503: { admin0: 'SS', admin1: 'SS05' },
        SS0504: { admin0: 'SS', admin1: 'SS05' },
        SS0505: { admin0: 'SS', admin1: 'SS05' },
        SS0601: { admin0: 'SS', admin1: 'SS06' },
        SS0602: { admin0: 'SS', admin1: 'SS06' },
        SS0603: { admin0: 'SS', admin1: 'SS06' },
        SS0604: { admin0: 'SS', admin1: 'SS06' },
        SS0605: { admin0: 'SS', admin1: 'SS06' },
        SS0606: { admin0: 'SS', admin1: 'SS06' },
        SS0607: { admin0: 'SS', admin1: 'SS06' },
        SS0608: { admin0: 'SS', admin1: 'SS06' },
        SS0609: { admin0: 'SS', admin1: 'SS06' },
        SS0701: { admin0: 'SS', admin1: 'SS07' },
        SS0702: { admin0: 'SS', admin1: 'SS07' },
        SS0703: { admin0: 'SS', admin1: 'SS07' },
        SS0704: { admin0: 'SS', admin1: 'SS07' },
        SS0705: { admin0: 'SS', admin1: 'SS07' },
        SS0706: { admin0: 'SS', admin1: 'SS07' },
        SS0707: { admin0: 'SS', admin1: 'SS07' },
        SS0708: { admin0: 'SS', admin1: 'SS07' },
        SS0709: { admin0: 'SS', admin1: 'SS07' },
        SS0710: { admin0: 'SS', admin1: 'SS07' },
        SS0711: { admin0: 'SS', admin1: 'SS07' },
        SS0712: { admin0: 'SS', admin1: 'SS07' },
        SS0801: { admin0: 'SS', admin1: 'SS08' },
        SS0802: { admin0: 'SS', admin1: 'SS08' },
        SS0803: { admin0: 'SS', admin1: 'SS08' },
        SS0804: { admin0: 'SS', admin1: 'SS08' },
        SS0805: { admin0: 'SS', admin1: 'SS08' },
        SS0806: { admin0: 'SS', admin1: 'SS08' },
        SS0901: { admin0: 'SS', admin1: 'SS09' },
        SS0902: { admin0: 'SS', admin1: 'SS09' },
        SS0903: { admin0: 'SS', admin1: 'SS09' },
        SS1001: { admin0: 'SS', admin1: 'SS10' },
        SS1002: { admin0: 'SS', admin1: 'SS10' },
        SS1003: { admin0: 'SS', admin1: 'SS10' },
        SS1004: { admin0: 'SS', admin1: 'SS10' },
        SS1005: { admin0: 'SS', admin1: 'SS10' },
        SS1006: { admin0: 'SS', admin1: 'SS10' },
        SS1007: { admin0: 'SS', admin1: 'SS10' },
        SS1008: { admin0: 'SS', admin1: 'SS10' },
        SS1009: { admin0: 'SS', admin1: 'SS10' },
        SS1010: { admin0: 'SS', admin1: 'SS10' },
      },
    },
  },
};

export default schema;
